### ISSUE TITLE
New version available

### ISSUE THREAD

**Issue by Alecaddd** [flathub/com.github.alecaddd.sequeler#4]
Not sure what would be the optimal process here, but I just released `v0.5.5` with a bunch of fixes and password encryption with `libsecret`.

Does the FlatPak get updated automatically? Should I do something particular? How do you want me to communicate future version releases?

**Comment by bilelmoussaoui** [comment]
I'm gonna update the application right now

**Comment by bilelmoussaoui** [comment]
In order to update the application. All you have to do is update the archive url and the sha256 checksums. Once it's done, you can create a PR and use Flathub builder to run a build test using `bot, build`. The build results can be checked on https://flathub.org/builds
For example for the latest PR that updates the application to v0.5.5 can be found here /#/builders/2/builds/2225
If you need any help with that just let me know.
